### PR TITLE
Coding style

### PR DESCRIPTION
**Pull request by enochtsang**
Updated coding style in scripts

### CODE REVIEW

**Comment by enochtsang** [comment]
@bryson189 @sneakyturtles

**Comment by JordanHeinrichs** [comment]
It looks good. Passes stages 1-2 and 4. As it is just coding style changes I can't image that there would be any bugs but I don't have unity set up and I am not up to date with this project to know what to check for. If either @bryson189 or @sneakyturtle can test it then I would be fine merging it in.

**Comment by bryson189** [comment]
Tested with Unity and it looks fine. I will change my branch to match this coding style.

**Comment by sneakyturtle** [comment]
Same. I will review and match my coding style to this.

**Pull request merged**
